server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://tutorial-eureka:8761/eureka
spring:
  application:
    name: SPRING-CLOUD-EUREKA-CLIENT-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: category
          uri: lb://SPRING-CLOUD-EUREKA-CLIENT-CATEGORY
          predicates:
            - Path=/category/**
        - id: author
          uri: lb://SPRING-CLOUD-EUREKA-CLIENT-AUTHOR
          predicates:
            - Path=/author/**
        - id: game
          uri: lb://SPRING-CLOUD-EUREKA-CLIENT-GAME
          predicates:
            - Path=/game/**
        - id: client
          uri: lb://SPRING-CLOUD-EUREKA-CLIENT-CLIENT
          predicates:
            - Path=/client/**
        - id: loan
          uri: lb://SPRING-CLOUD-EUREKA-CLIENT-LOAN
          predicates:
            - Path=/loan/**
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      enabled: true
